---
title: "Cover letter: HBC paper"
date: "`r Sys.time()`"
bibliography: hbc-references.bib
csl: vancouver.csl
output: word_document
---

Dear Editors of Royal Society Interface, 

Hereby, we submit our manuscript entitled '**High duty-cycle bats in the field do not alter echolocation calls when flying in groups**' for consideration as a research report in your journal. 

Individuals in active sensing groups, be they drones, robots or echolocating bats - face the common problem of jamming each other. Individuals in most man-made groups can perhaps overcome jamming through the use of unique frequencies or co-ordinating emission times of their probes. Animals in groups rarely have the luxury of doing so. Echolocating bats especially face a problem when in groups as the range of frequency shifting (among other strategies) each individual can perform is limited by their morphology and energetics [@jones2006evolution;@currie2020echolocation]. We investigate how one group of echolocating bats, the 'high duty-cycle' bats manage to echolocate in groups. High duty-cycle bats are particularly susceptible to jamming as they emit long calls, but also have very short silences between calls. This rapid emission of long calls means even small groups of a few bats present jamming-type situations. Despite this expectation, tens of high duty-cycle bats are often seen to fly together in nature. We ask if high duty-cycle  bats show alterations in their echolocation in the presence of other bats. 

The call overlaps that jam bats, have had a similar effect on researchers over the past decades, who have at most studied groups of two to three CF-FM bats together under lab conditions [@jones1994individual;@fawcett2015echolocation]. Analysing overlapping echolocation calls is non-trivial, and has been a major obstacle to the study of group echolocation. In our multi-disciplinary study, we bring together a combination of methodological advances by 1) studying groups of bats in the field, 2) developing meaningful ways to analyse audio data with overlapping calls and 3) putting the observed data in context of physically based simulations. We find that bats in groups of up to 4 individuals do not alter their call parameters in the presence of each other. Both acoustic analyses support  these results. Our simulations as well show that the observed patterns can be explained by a 'null' model where individuals do not show special responses to each other. We then posit that the 'standard' sensorimotor routines bats use when alone (reliance on spatial memory and ability to handle 'self-jamming' by competing returning echoes of different intensities) allows them to also handle occasional disruptions from group members' calls.  

We believe our study is of interest to the Journal due to its interdisciplinarity, at the boundary between acoustics, bioacoustics, and sensory biology, and specifically adding to the methods in analysing complex audio data [@madhusudhana2021improve]. Our approaches and results may be of potential interest to the biology, bio-engineering and physics communities in general.

Thanking you for your time, and looking forward to hear from you, 

# References
